#!/usr/bin/python

import sys
import common  # mangle sys.path

from charmhelpers.core import hookenv
from charmhelpers import fetch

hooks = hookenv.Hooks()
log = hookenv.log


@hooks.hook('install')
def install():
    log('Installing postfix')
    hookenv.status_set('maintenance', 'installing')
    fetch.apt_install(fetch.filter_installed_packages(['postfix', 'postfix-pcre']))
    hookenv.status_set('maintenance', 'installed')


if __name__ == "__main__":
    hooks.execute(sys.argv)
