#!/usr/bin/python

import sys

from common import start_postfix
from charmhelpers.core import hookenv

hooks = hookenv.Hooks()


@hooks.hook('start')
def start():
    start_postfix()
    hookenv.open_port(25)


if __name__ == "__main__":
    hooks.execute(sys.argv)
