#!/usr/bin/python

import sys

from common import stop_postfix
from charmhelpers.core import hookenv

hooks = hookenv.Hooks()
log = hookenv.log


@hooks.hook('stop')
def stop():
    hookenv.close_port(25)
    stop_postfix()


if __name__ == "__main__":
    hooks.execute(sys.argv)
